### ISSUE TITLE
Petite erreur 

### ISSUE THREAD

**Issue by JFNigaise** [nliautaud/nppmanuel#5]
Dans le dernier exemple du tableau du chapitre **Ensembles et groupes**, l'explication de l'expression est incorrecte.

#a(bc)+ désigne “la lettre a puis au moins une fois le groupe de lettres ab”. Cela pourrait correspondre à abc, abcbc, abcbcbcbcbc, etc.

Alors que cette expression désigne “la lettre a puis au moins une fois le groupe de lettres bc”. Les exemples qui suivent sont justes.

**Comment by nliautaud** [comment]
Bien vu, merci.
